### ISSUE TITLE
We need multiple types of missiles

### ISSUE THREAD

**Issue by chwerth** [chwerth/RAstral_Rampart#12]
Right now I only use one as a first step. Each missile will end up with different properties - like different speeds, damage, health, etc.

Since we're going to start with three missiles, there could be:

1. A slow, but damaging missile
2. A medium speed and medium damage missile
3. A fast, but low damage missile

Seems like a good start

**Comment by Rw552** [comment]
I’ll work on this tomorrow, starting with having a few different types. Then I’ll work on the different properties like speed

**Comment by chwerth** [comment]
> I’ll work on this tomorrow, starting with having a few different types. Then I’ll work on the different properties like speed

Lit. There's three missiles in the assets folder, can start with using those. A separate issue to solve that's related to this is animating the missiles as they fly using the varied images included.
