### ISSUE TITLE
Sometimes when I fire the gun, the game crashes.

### ISSUE THREAD

**Issue by chwerth** [chwerth/RAstral_Rampart#39]
![crash](https://user-images.githubusercontent.com/48846148/81618724-95cbad00-93ad-11ea-83ac-e2ac7c69bbe6.png)

Quick google search revealed that this is a common issue? https://stackoverflow.com/questions/56027626/how-to-stop-the-fatal-python-error-pyeval-savethread-null-tstate

**Comment by chwerth** [comment]
Appears to only happen in the menu?

**Comment by Rw552** [comment]
question, is it happening when you fire and hit the 'play' button? cause if so, I think I fixed the issue

**Comment by chwerth** [comment]
Correct @Rw552

**Comment by Rw552** [comment]
> Correct @Rw552 

Cool. I fixed that in the branch I just made a PR for. It was an issue with BG music audio file

**Comment by chwerth** [comment]
This is fixed by using python 3.7.5+ and @Rw552 change with the music file
