### ISSUE TITLE
Might want to rename the game

### ISSUE THREAD

**Issue by chwerth** [chwerth/RAstral_Rampart#50]
Someone already used the name

https://play.google.com/store/apps/details?id=com.ketchapp.spinnygun&hl=en_US

Could keep track of ideas in this thread.

- Spinblast

**Comment by Rw552** [comment]
I agree we might want to find another name. I'm thinking something without 'spin' as the gun doesn't really spin in a full circle, it just oscillates back and forth.

**Comment by chwerth** [comment]
Good point
