### ISSUE TITLE
Should we be using Sprites for game objects?

### ISSUE THREAD

**Issue by chwerth** [chwerth/RAstral_Rampart#51]
Basic explanation: 
https://stackoverflow.com/questions/41986383/pygame-what-is-the-difference-between-an-image-and-a-sprite

Official documentation:
https://www.pygame.org/docs/ref/sprite.html#pygame.sprite.Sprite
https://www.pygame.org/docs/tut/SpriteIntro.html

Example with a player and bullets:
http://programarcadegames.com/python_examples/f.php?file=bullets.py

It's a built-in pygame module for game objects. Did not even really realize it was a thing. Might be unnecessary, but could be worth looking into if there are any advantages

Found an animation example that uses sprites:
https://stackoverflow.com/questions/14044147/animated-sprite-from-few-images

Might be relevant to #12 and #15

**Comment by Rw552** [comment]
I'm going to try my hand at converting to sprites. wish me luck lol

**Comment by Rw552** [comment]
@chwerth take a look at this. it shows how collision works with sprites, as well as groups

http://programarcadegames.com/python_examples/f.php?file=sprite_collect_blocks.py

**Comment by Rw552** [comment]
here's the full tutorial http://programarcadegames.com/index.php?chapter=introduction_to_sprites

**Comment by chwerth** [comment]
That's probably much simpler than what I was doing. Cool. If we did that, would likely need to refactor projectile a bit. It just exists as a radius and a position, which we use to draw circles. That's why the `intersects` function works

**Comment by Rw552** [comment]
we'll need to refactor a lot I think lol. I'm working through a test file to make sure I have a full grasp on how to manipulate Sprites, and then I'll continue working on the sprite-conversion branch i made

**Comment by chwerth** [comment]
You are on a roll today lol
